# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/betting_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Kafka completely
spring.kafka.enabled=false
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

# Disable MongoDB
spring.data.mongodb.repositories.enabled=false

# Server
server.port=8080
spring.threads.virtual.enabled=true